### ISSUE TITLE
SRO uninstall procedure configurable?

### ISSUE THREAD

**Issue by jnunyez** [openshift/special-resource-operator#109]
I was trying to understand how the uninstall procedure of  SRO operator worked (deleting CSV and subscription objects). 

Consider a scenario where there are multiple specialresource CRs created by other operators that are consuming SRO. Also consider that in this scenario we wan to keep everything clean after uninstalling (i.e., deleting CRs and CRDs). When SRO operator is uninstalled (subscription and CSV) the specialresource CRs are deleted. Both the CRs and CRD are kept.  

I understand this is a cautious strategy.  An uninstall strategy there could be that CRs might be deleted by the operator that created them. But if those CRs are there to consume SRO only.  Also the CRD from the SRO will still be there and I'm unsure what event could trigger its deletion.    
I was wondering if  there is a possibility to make configurable the deletion of the CRs consuming SRO from the same SRO subscription object in a less cautious way.

**Comment by bthurber** [comment]
Associated RFE BZ:  https://bugzilla.redhat.com/show_bug.cgi?id=2052782

**Comment by bthurber** [comment]
After further investigation, the current behavior is desired meaning that special resource artifacts are left in-place to prevent any unwanted outages in case the operator is uninstalled unintentionally.  This is common among operators in general to prevent a data loss situation.  In addition to, SRO will be moving to a new code base in the future and don't expect any additional enhancements outside of what is planned with the next OCP release with the current code base.
