### ISSUE TITLE
Does SRO support build config on Vanilla K8S? If so, then is there any chance to port it? If so what would be time schedule?

### ISSUE THREAD

**Issue by rpieczon** [openshift/special-resource-operator#129]

**Comment by bthurber** [comment]
The short answer is no however shipwright is something available upstream and also supported in OCP 4.10.  We are working to upstream SRO into kubernetes.  I would recommend filing an issue here for shipwright support:  https://github.com/kubernetes-sigs/special-resource-operator/issues
