### ISSUE TITLE
Consider archiving this repo

### ISSUE THREAD

**Issue by jlebon** [openshift/special-resource-operator#252]
This repo doesn't look used anymore. Let's update the README to point folks elsewhere and archive it?

**Comment by jlebon** [comment]
The reason this showed up on my radar is that [it references `machine-os-content`](https://github.com/openshift/special-resource-operator/blob/c9e8fde259f27affb59c5fd06dd2b1744aa5319f/pkg/registry/registry.go#L133-L158), which we're trying to remove.

**Comment by bthurber** [comment]
> The reason this showed up on my radar is that [it references `machine-os-content`](https://github.com/openshift/special-resource-operator/blob/c9e8fde259f27affb59c5fd06dd2b1744aa5319f/pkg/registry/registry.go#L133-L158), which we're trying to remove.

@mrunalp do you have admin rights to archive this repo?  

@qbarrand FYI
