### ISSUE TITLE
[Release] Please prepare bundle for OCP 4.10

### ISSUE THREAD

**Issue by thegreyd** [openshift/special-resource-operator#57]
Now that we are fully branched for 4.10, please prepare your operator to supply a 4.10 bundle (https://github.com/openshift/special-resource-operator/tree/release-4.10/bundle), so that 4.10 operator publishing works

**Comment by thegreyd** [comment]
cc @dagrayvid @zvonkok @Veritasosrb

**Comment by bthurber** [comment]
Covered here: https://github.com/openshift-psap/special-resource-operator/pull/130

@pacevedom is this something we need to cherrypick for downstream?

**Comment by pacevedom** [comment]
This is the [downstream PR](https://github.com/openshift/special-resource-operator/pull/68), pending 1 approval.

**Comment by bthurber** [comment]
@pacevedom I am unable to close as resolved.  Are you able to close this issue as it is now complete?

**Comment by pacevedom** [comment]
@bthurber can't see it either. Must be related to admin permissions.

**Comment by bthurber** [comment]
@dagrayvid do you have the ability to close this?
